language: python
python:
  - "3.5"
  - "nightly"
install:
  - pip install pip --upgrade
  - pip install .
  - pip install coveralls

# command to run tests
script: coverage run --source=futurefinity setup.py test

after_success:
  coveralls
