sudo: false

matrix:
  allow_failures:
    - python: nightly

  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: PYTHONVER=3.5.1

    - os: osx
      osx_image: xcode7.3
      language: generic
      env: PYTHONVER=3.5.2

    - os: linux
      python: 3.5.1

    - os: linux
      python: 3.5.2

    - os: linux
      python: nightly

language: python

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $PYTHONVER ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global $PYTHONVER  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"   ; fi
  - python -m pip install pip setuptools --upgrade
  - python -m pip install .[test]
  - python -m pip install coveralls

# command to run tests
script: python -m coverage run --source=futurefinity -m futurefinity.tests

after_success:
  coveralls
